# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Xonder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Xonder

 pod 'IQKeyboardManagerSwift'
    pod 'Moya', '~> 13.0'
    pod 'PKHUD', '~> 5.0'
    pod 'JGProgressHUD'
    pod 'SVPinView', '~> 1.0'
    pod 'DropDown'
    pod 'GooglePlaces'
    pod 'GoogleMaps'
    pod 'KAPinField'

end
